### ISSUE TITLE
Can I set transform:null for a custom method?

### ISSUE THREAD

**Issue by pcorey** [ongoworks/meteor-security#12]
Documents passed to custom methods defined with Security.defineMethod are transformed by default. Is there a way to set transform: null, like I would on a normal <collection>.deny call?

**Comment by aldeed** [comment]
No. We can add this, but it will not be quite as simple as you might think because a single "real" deny function runs all of the deny functions from this package. Maybe we can have the single deny function with `transform: null` by default, and manually transform the doc before passing it to any security rules that request a transform.

**Comment by aldeed** [comment]
Implemented. See updated docs: https://github.com/ongoworks/meteor-security#transformations

**Comment by pcorey** [comment]
Awesome! Thanks a lot!
